


# params:
#     context_window: 5
#     train_split: 0.8
#     val_split: 0.1
#     hidden_dim: 16

#     n_runs: 1
#     n_epochs: 1000
#     hidden_size: 128
#     lr: 0.001    
    
params:
    context_window: 5
    train_split: 0.8
    val_split: 0.1
    hidden_dim: 128

    n_runs: 1
    n_epochs: 1000
    hidden_size: 128
    lr: 0.0001